const FORM_SUBMIT = "FORM_SUBMIT"
const FORM_DELETE_TITLE = "DELETE_TITLE"
const FORM_UPDATE_TITLE = "FORM_UPDATE_TITLE"
const FORM_SET_TITLE_DETAILS = "FORM_SET_TITLE_DETAILS";
const FORM_SHOW_TITLE_DETAILS = "FORM_SHOW_TITLE_DETAILS";
const FORM_SET_INITIAL_DATA = "FORM_SET_INITIAL_DATA";
const FORM_SELECTED_SEASON = "FORM_SELECTED_SEASON"; 
const FORM_SELECTED_CHAPTER = "FORM_SELECTED_CHAPTER";
const FORM_UPDATE_FAVORITE = "FORM_UPDATE_FAVORITE"
const FORM_SET_WATCHED = "FORM_SET_WATCHED"

export {FORM_DELETE_TITLE, FORM_SUBMIT, FORM_UPDATE_TITLE, FORM_SET_TITLE_DETAILS, FORM_SHOW_TITLE_DETAILS, FORM_SET_INITIAL_DATA, FORM_SELECTED_CHAPTER, FORM_SELECTED_SEASON, FORM_UPDATE_FAVORITE, FORM_SET_WATCHED}