const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
const FETCH_DATA_EMPTY = "FETCH_DATA_EMPTY"
const FETCH_DATA_DETAILS = "FETCH_DATA_DETAILS"

export {FETCH_DATA_FAILURE, FETCH_DATA_REQUEST, FETCH_DATA_SUCCESS, FETCH_DATA_EMPTY, FETCH_DATA_DETAILS}